// Generated by CoffeeScript 1.6.3
(function() {
  var ClientMC, WebSocket, ever, zlib;

  WebSocket = require('ws');

  ever = require('ever');

  zlib = require('zlib-browserify');

  module.exports = function(game, opts) {
    return new ClientMC(game, opts);
  };

  ClientMC = (function() {
    function ClientMC(game, opts) {
      var _base;
      this.game = game;
      this.opts = opts;
      if ((_base = this.opts).url == null) {
        _base.url = 'ws://localhost:1234';
      }
      this.enable();
    }

    ClientMC.prototype.enable = function() {
      this.ws = new WebSocket(this.opts.url);
      ever(this.ws).on('open', function() {
        return console.log('WebSocket connected');
      });
      ever(this.ws).on('error', function(err) {
        return console.log('WebSocket error', err);
      });
      return ever(this.ws).on('message', function(event, flags) {
        var compressed, name, packet, payload;
        packet = JSON.parse(event.data);
        name = packet[0], payload = packet[1];
        if (name === 'map_chunk_bulk') {
          console.log(payload);
          compressed = payload.data.compressedChunkData;
          console.log('map_chunk_bulk', compressed.length);
          return zlib.inflate(compressed, function(err, result) {
            var addArray, at, biomeArray, chunksData, groundUpContinuous, lightArray, maxLength, metaArray, miniChunks, skyArray, skyLightSent, typeArray;
            console.log('  decomp', result.length);
            console.log(result);
            chunksData = new Uint8Array(result);
            at = 0;
            miniChunks = [];
            maxLength = result.length;
            skyLightSent = payload.skyLightSent;
            groundUpContinuous = true;
            while (at < maxLength) {
              typeArray = chunksData.subarray(at, at += 16 * 16 * 16 * 1);
              metaArray = chunksData.subarray(at, at += 16 * 16 * 16 / 2);
              lightArray = chunksData.subarray(at, at += 16 * 16 * 16 / 2);
              if (skyLightSent) {
                skyArray = chunksData.subarray(at, at += 16 * 16 * 16 / 2);
              }
              addArray = chunksData.subarray(at, at += 16 * 16 * 16 / 2);
              if (groundUpContinuous) {
                biomeArray = chunksData.subarray(at, at += 256);
              }
              miniChunks.push({
                types: typeArray
              });
            }
            window.result = result;
            window.x = this;
            debugger;
          });
        }
      });
    };

    ClientMC.prototype.disable = function() {};

    return ClientMC;

  })();

}).call(this);
