// Generated by CoffeeScript 1.6.3
(function() {
  var ClientMC, WebSocket, ever;

  WebSocket = require('ws');

  ever = require('ever');

  module.exports = function(game, opts) {
    return new ClientMC(game, opts);
  };

  ClientMC = (function() {
    function ClientMC(game, opts) {
      var _base;
      this.game = game;
      this.opts = opts;
      if ((_base = this.opts).url == null) {
        _base.url = 'ws://localhost:1234';
      }
      this.enable();
    }

    ClientMC.prototype.enable = function() {
      this.ws = new WebSocket(this.opts.url);
      ever(this.ws).on('open', function() {
        return console.log('WebSocket connected');
      });
      ever(this.ws).on('error', function(err) {
        return console.log('WebSocket error', err);
      });
      return ever(this.ws).on('message', function(event, flags) {
        var name, packet, payload;
        packet = JSON.parse(event.data);
        name = packet[0], payload = packet[1];
        if (name === 'map_chunk_bulk') {
          return console.log('map_chunk_bulk', payload.data.compressedChunkData.length);
        }
      });
    };

    ClientMC.prototype.disable = function() {};

    return ClientMC;

  })();

}).call(this);
