// Generated by CoffeeScript 1.6.3
(function() {
  var ever, zlib;

  zlib = require('zlib-browserify');

  ever = require('ever');

  module.exports = function() {
    return ever(this).on('message', function(ev) {
      var compressedArrayBuffer, compressedArrayView, compressedBuffer, id,
        _this = this;
      compressedArrayBuffer = ev.data.compressed;
      compressedArrayView = new Uint8Array(compressedArrayBuffer);
      compressedBuffer = new Buffer(compressedArrayView);
      id = ev.data.id;
      return zlib.inflate(compressedBuffer, function(err, decompressed) {
        var decompressedBuffer;
        if (err) {
          _this.postMessage({
            id: id,
            err: err.toString()
          });
          return;
        }
        decompressedBuffer = decompressed.buffer;
        return _this.postMessage({
          id: id,
          decompressed: decompressedBuffer
        }, [decompressedBuffer]);
      });
    });
  };

}).call(this);
